version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: social_listening_db
    environment:
      POSTGRES_USER: sl_user
      POSTGRES_PASSWORD: sl_pass
      POSTGRES_DB: social_listening
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
